CDLC_JSON_1 = {
    "artist": "Porno Graffiti",
    "0": "Porno Graffiti",
    "title": "Hitori No Yoru(Great Teacher Onizuka)",
    "1": "Hitori No Yoru(Great Teacher Onizuka)",
    "album": "Romantist Egoist",
    "2": "Romantist Egoist",
    "tuning": "estandard",
    "3": "estandard",
    "parts": ",lead,rhythm,bass,",
    "4": ",lead,rhythm,bass,",
    "dd": "no",
    "5": "no",
    "platforms": ",pc,mac,",
    "6": ",pc,mac,",
    "rating": 5057,
    "7": 5057,
    "updated": 1398197782,
    "8": 1398197782,
    "member": "BMB",
    "9": "BMB",
    "furl": "hitori-no-yorugreat-teacher-onizuka",
    "10": "hitori-no-yorugreat-teacher-onizuka",
    "id": 3492,
    "11": 3492,
    "added": 1398197770,
    "12": 1398197770,
    "version": "1.0",
    "13": "1.0",
    "downloads": 837,
    "14": 837,
    "official": "No",
    "15": "No",
    "direct": "",
    "16": "",
    "music_video": "http://youtu.be/kDh3D2ewiNs",
    "17": "http://youtu.be/kDh3D2ewiNs",
    "instrument_info": "",
    "18": "",
    "album_art": "http://www.jpopasia.com/img/album-covers/2/16933-hitorinoyoru-ywbi.jpg",
    "19": "http://www.jpopasia.com/img/album-covers/2/16933-hitorinoyoru-ywbi.jpg",
    "like_rel_id": None,
    "20": None,
    "follow": None,
    "21": None,
    "record_id": None,
    "22": None,
    "saved": None,
    "23": None,
}

CDLC_JSON_2 = {
    "artist": "Blur",
    "0": "Blur",
    "title": "Song 2",
    "1": "Song 2",
    "album": "Blur",
    "2": "Blur",
    "tuning": "estandard",
    "3": "estandard",
    "parts": "lead,bass,vocals",
    "4": "lead,bass,vocals",
    "dd": "yes",
    "5": "yes",
    "platforms": ",pc,mac,xbox360,ps3,",
    "6": ",pc,mac,xbox360,ps3,",
    "rating": 49424,
    "7": 49424,
    "updated": 1318910400,
    "8": 1318910400,
    "member": "CustomsForge",
    "9": "CustomsForge",
    "furl": "song-2",
    "10": "song-2",
    "id": 8623,
    "11": 8623,
    "added": 1318910400,
    "12": 1318910400,
    "version": "1.0",
    "13": "1.0",
    "downloads": 3084,
    "14": 3084,
    "official": "Yes",
    "15": "Yes",
    "direct": "http://www.theriffrepeater.com/rocksmith-2014-setlist/rocksmith-setlist/",
    "16": "http://www.theriffrepeater.com/rocksmith-2014-setlist/rocksmith-setlist/",
    "music_video": "https://www.youtube.com/watch?v=SSbBvKaM6sk",
    "17": "https://www.youtube.com/watch?v=SSbBvKaM6sk",
    "instrument_info": None,
    "18": None,
    "album_art": "http://upload.wikimedia.org/wikipedia/en/b/b1/Blur_Blur.jpg",
    "19": "http://upload.wikimedia.org/wikipedia/en/b/b1/Blur_Blur.jpg",
    "like_rel_id": None,
    "20": None,
    "follow": None,
    "21": None,
    "record_id": None,
    "22": None,
    "saved": None,
    "23": None,
}

CDLC_JSON_3 = {
    "artist": "Yellowcard",
    "0": "Yellowcard",
    "title": "Hang You Up",
    "1": "Hang You Up",
    "album": "When You&#39;re Through Thinking Say Yes",
    "2": "When You&#39;re Through Thinking Say Yes",
    "tuning": "estandard",
    "3": "estandard",
    "parts": ",lead,rhythm,vocals,",
    "4": ",lead,rhythm,vocals,",
    "dd": "yes",
    "5": "yes",
    "platforms": ",pc,",
    "6": ",pc,",
    "rating": 60033,
    "7": 60033,
    "updated": 1588013991,
    "8": 1588013991,
    "member": "llfnv321",
    "9": "llfnv321",
    "furl": "hang-you-up",
    "10": "hang-you-up",
    "id": 49410,
    "11": 49410,
    "added": 1588013991,
    "12": 1588013991,
    "version": "1.0",
    "13": "1.0",
    "downloads": 52,
    "14": 52,
    "official": "No",
    "15": "No",
    "direct": "",
    "16": "",
    "music_video": "",
    "17": "",
    "instrument_info": "",
    "18": "",
    "album_art": "http://i.imgur.com/3251bFh.jpg",
    "19": "http://i.imgur.com/3251bFh.jpg",
    "notes": "",
    "20": "",
    "collections": 24,
}
